/**
 * lib/products.js — Auralis curated product dataset
 *
 * 70 products across 7 brands, 6 categories, 11 colours, 5 style tags.
 * No imports — self-contained static data.
 *
 * Schema matches normalised product shape from lib/normalisers.js:
 *   id, title, price, image, brand, retailer, productUrl, affiliateUrl,
 *   category, color, tags
 *
 * Brands    : Zara · COS · Arket · Mango · Reformation · Toteme · & Other Stories
 * Categories: Coats & Jackets · Tops · Dresses · Trousers · Knitwear · Activewear
 * Colours   : black · white · cream · beige · grey · blue · green · red · pink · brown · burgundy
 * Tags      : minimal · luxe · streetwear · classic · sporty  (1–2 per product)
 */

export const PRODUCTS = [

  // ─── ZARA ────────────────────────────────────────────────────────────────────

  {
    id: "prod-z-001",
    title: "Oversized Cargo Trousers",
    price: "£49.99",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "beige",
    tags: ["streetwear"],
  },
  {
    id: "prod-z-002",
    title: "Ruched Satin Slip Dress",
    price: "£69.99",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "black",
    tags: ["luxe"],
  },
  {
    id: "prod-z-003",
    title: "Longline Faux Leather Jacket",
    price: "£89.99",
    image: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/outerwear",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "black",
    tags: ["streetwear"],
  },
  {
    id: "prod-z-004",
    title: "Ribbed Crop Top",
    price: "£17.99",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "white",
    tags: ["sporty"],
  },
  {
    id: "prod-z-005",
    title: "Open Knit Relaxed Jumper",
    price: "£35.99",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "cream",
    tags: ["minimal"],
  },
  {
    id: "prod-z-006",
    title: "High Waist Wide Leg Trousers",
    price: "£45.99",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "grey",
    tags: ["minimal"],
  },
  {
    id: "prod-z-007",
    title: "Asymmetric Satin Midi Dress",
    price: "£79.99",
    image: "https://images.unsplash.com/photo-1550614000-4895a10e1bfd?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "burgundy",
    tags: ["luxe"],
  },
  {
    id: "prod-z-008",
    title: "Seamless Long Sleeve Training Top",
    price: "£25.99",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/activewear",
    affiliateUrl: "",
    category: "Activewear",
    color: "black",
    tags: ["sporty"],
  },
  {
    id: "prod-z-009",
    title: "Double Breasted Checked Blazer",
    price: "£99.99",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/outerwear",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "grey",
    tags: ["classic"],
  },
  {
    id: "prod-z-010",
    title: "Broderie Anglaise Tie Blouse",
    price: "£35.99",
    image: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&q=80",
    brand: "Zara",
    retailer: "Zara",
    productUrl: "https://www.zara.com/gb/en/woman/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "white",
    tags: ["classic"],
  },

  // ─── COS ─────────────────────────────────────────────────────────────────────

  {
    id: "prod-c-001",
    title: "Tailored Straight-Leg Trousers",
    price: "£95.00",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "black",
    tags: ["minimal"],
  },
  {
    id: "prod-c-002",
    title: "Oversized Merino Wool Jumper",
    price: "£110.00",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "grey",
    tags: ["minimal"],
  },
  {
    id: "prod-c-003",
    title: "Relaxed Fit Linen Shirt",
    price: "£75.00",
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "white",
    tags: ["minimal", "classic"],
  },
  {
    id: "prod-c-004",
    title: "Structured Wool Blend Overcoat",
    price: "£225.00",
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/coats",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "beige",
    tags: ["minimal", "classic"],
  },
  {
    id: "prod-c-005",
    title: "Draped Jersey Midi Dress",
    price: "£89.00",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "black",
    tags: ["minimal"],
  },
  {
    id: "prod-c-006",
    title: "Cotton Poplin Collarless Blouse",
    price: "£65.00",
    image: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "cream",
    tags: ["minimal"],
  },
  {
    id: "prod-c-007",
    title: "Wide Leg Cropped Trousers",
    price: "£85.00",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "grey",
    tags: ["minimal"],
  },
  {
    id: "prod-c-008",
    title: "Fine Knit Roll Neck Sweater",
    price: "£95.00",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "black",
    tags: ["minimal", "classic"],
  },
  {
    id: "prod-c-009",
    title: "Tailored Longline Blazer",
    price: "£175.00",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/coats",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "red",
    tags: ["minimal"],
  },
  {
    id: "prod-c-010",
    title: "Seamless Rib Performance Top",
    price: "£55.00",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80",
    brand: "COS",
    retailer: "COS",
    productUrl: "https://www.cos.com/en_gbp/women/activewear",
    affiliateUrl: "",
    category: "Activewear",
    color: "grey",
    tags: ["sporty", "minimal"],
  },

  // ─── ARKET ───────────────────────────────────────────────────────────────────

  {
    id: "prod-a-001",
    title: "Merino Ribbed Crew Neck",
    price: "£95.00",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "cream",
    tags: ["classic"],
  },
  {
    id: "prod-a-002",
    title: "Cotton Oxford Button-Down Shirt",
    price: "£75.00",
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "blue",
    tags: ["classic"],
  },
  {
    id: "prod-a-003",
    title: "Slim Wide Leg Tailored Trousers",
    price: "£85.00",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "black",
    tags: ["classic", "minimal"],
  },
  {
    id: "prod-a-004",
    title: "Recycled Wool Blend Coat",
    price: "£195.00",
    image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/coats",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "grey",
    tags: ["classic"],
  },
  {
    id: "prod-a-005",
    title: "Linen Shift Dress",
    price: "£95.00",
    image: "https://images.unsplash.com/photo-1612722432474-b971cdcea546?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "white",
    tags: ["minimal"],
  },
  {
    id: "prod-a-006",
    title: "Chunky Cotton Knit Cardigan",
    price: "£120.00",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "brown",
    tags: ["classic"],
  },
  {
    id: "prod-a-007",
    title: "Organic Cotton Relaxed Tee",
    price: "£35.00",
    image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "beige",
    tags: ["minimal"],
  },
  {
    id: "prod-a-008",
    title: "Double Breasted Tailored Blazer",
    price: "£165.00",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/coats",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "blue",
    tags: ["classic"],
  },
  {
    id: "prod-a-009",
    title: "Essential Training Leggings",
    price: "£55.00",
    image: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/activewear",
    affiliateUrl: "",
    category: "Activewear",
    color: "black",
    tags: ["sporty"],
  },
  {
    id: "prod-a-010",
    title: "Jersey T-Shirt Dress",
    price: "£65.00",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80",
    brand: "Arket",
    retailer: "Arket",
    productUrl: "https://www.arket.com/en_gbp/women/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "grey",
    tags: ["minimal"],
  },

  // ─── MANGO ───────────────────────────────────────────────────────────────────

  {
    id: "prod-m-001",
    title: "Structured Linen Trousers",
    price: "£59.99",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "beige",
    tags: ["classic"],
  },
  {
    id: "prod-m-002",
    title: "Faux Leather Longline Blazer",
    price: "£89.99",
    image: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/jackets",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "black",
    tags: ["streetwear"],
  },
  {
    id: "prod-m-003",
    title: "Ruffled Wrap Midi Dress",
    price: "£79.99",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "red",
    tags: ["luxe"],
  },
  {
    id: "prod-m-004",
    title: "Knitted V-Neck Vest Top",
    price: "£35.99",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "green",
    tags: ["classic"],
  },
  {
    id: "prod-m-005",
    title: "Fitted Mock Neck Long Sleeve Top",
    price: "£29.99",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "black",
    tags: ["minimal", "classic"],
  },
  {
    id: "prod-m-006",
    title: "Flowing Wrap Midi Dress",
    price: "£69.99",
    image: "https://images.unsplash.com/photo-1612722432474-b971cdcea546?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "brown",
    tags: ["classic"],
  },
  {
    id: "prod-m-007",
    title: "Relaxed Cargo Wide Leg Trousers",
    price: "£55.99",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "green",
    tags: ["streetwear"],
  },
  {
    id: "prod-m-008",
    title: "Padded Technical Sports Jacket",
    price: "£99.99",
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/jackets",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "black",
    tags: ["sporty", "streetwear"],
  },
  {
    id: "prod-m-009",
    title: "Backless Strappy Halter Top",
    price: "£39.99",
    image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "white",
    tags: ["luxe"],
  },
  {
    id: "prod-m-010",
    title: "High Waist Seamless Training Shorts",
    price: "£25.99",
    image: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=600&q=80",
    brand: "Mango",
    retailer: "Mango",
    productUrl: "https://www.mango.com/en_gb/women/activewear",
    affiliateUrl: "",
    category: "Activewear",
    color: "grey",
    tags: ["sporty"],
  },

  // ─── REFORMATION ─────────────────────────────────────────────────────────────

  {
    id: "prod-r-001",
    title: "Silk Cowl Neck Midi Dress",
    price: "£245.00",
    image: "https://images.unsplash.com/photo-1550614000-4895a10e1bfd?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "cream",
    tags: ["luxe", "minimal"],
  },
  {
    id: "prod-r-002",
    title: "Linen Wide Leg Trousers",
    price: "£148.00",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "white",
    tags: ["minimal"],
  },
  {
    id: "prod-r-003",
    title: "Ribbed Bodycon Mini Dress",
    price: "£178.00",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "black",
    tags: ["luxe"],
  },
  {
    id: "prod-r-004",
    title: "Puff Sleeve Linen Blouse",
    price: "£128.00",
    image: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "pink",
    tags: ["luxe"],
  },
  {
    id: "prod-r-005",
    title: "Smocked Waist Flowy Midi Dress",
    price: "£195.00",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "blue",
    tags: ["luxe"],
  },
  {
    id: "prod-r-006",
    title: "Tie-Front Knit Cardigan",
    price: "£168.00",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "cream",
    tags: ["minimal"],
  },
  {
    id: "prod-r-007",
    title: "Fitted Cropped Denim Jacket",
    price: "£178.00",
    image: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/outerwear",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "blue",
    tags: ["minimal"],
  },
  {
    id: "prod-r-008",
    title: "Cropped Stretch Rib Top",
    price: "£88.00",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "black",
    tags: ["minimal"],
  },
  {
    id: "prod-r-009",
    title: "Tiered Linen Maxi Dress",
    price: "£275.00",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "burgundy",
    tags: ["luxe"],
  },
  {
    id: "prod-r-010",
    title: "Stretch Jersey Active Legging",
    price: "£98.00",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80",
    brand: "Reformation",
    retailer: "Reformation",
    productUrl: "https://www.thereformation.com/products/activewear",
    affiliateUrl: "",
    category: "Activewear",
    color: "black",
    tags: ["sporty", "minimal"],
  },

  // ─── TOTEME ──────────────────────────────────────────────────────────────────

  {
    id: "prod-t-001",
    title: "Scarf Collar Wool Coat",
    price: "£590.00",
    image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/coats",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "cream",
    tags: ["luxe", "minimal"],
  },
  {
    id: "prod-t-002",
    title: "Crinkled Silk Shirt",
    price: "£295.00",
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "beige",
    tags: ["luxe"],
  },
  {
    id: "prod-t-003",
    title: "Draped Silk Blend Maxi Dress",
    price: "£450.00",
    image: "https://images.unsplash.com/photo-1550614000-4895a10e1bfd?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "black",
    tags: ["luxe", "minimal"],
  },
  {
    id: "prod-t-004",
    title: "Tapered Pressed-Crease Trousers",
    price: "£295.00",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "grey",
    tags: ["luxe"],
  },
  {
    id: "prod-t-005",
    title: "Ribbed Cashmere Blend Jumper",
    price: "£380.00",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "burgundy",
    tags: ["luxe"],
  },
  {
    id: "prod-t-006",
    title: "Classic Column Midi Dress",
    price: "£395.00",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "white",
    tags: ["luxe"],
  },
  {
    id: "prod-t-007",
    title: "Wide Leg Pleat Front Trousers",
    price: "£275.00",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "black",
    tags: ["luxe", "minimal"],
  },
  {
    id: "prod-t-008",
    title: "Cable Knit Turtleneck Sweater",
    price: "£340.00",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "cream",
    tags: ["luxe", "classic"],
  },
  {
    id: "prod-t-009",
    title: "Belted Double Breasted Coat",
    price: "£545.00",
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/coats",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "grey",
    tags: ["luxe", "classic"],
  },
  {
    id: "prod-t-010",
    title: "Washed Silk Slip Top",
    price: "£245.00",
    image: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&q=80",
    brand: "Toteme",
    retailer: "Toteme",
    productUrl: "https://toteme-studio.com/products/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "pink",
    tags: ["luxe"],
  },

  // ─── & OTHER STORIES ─────────────────────────────────────────────────────────

  {
    id: "prod-os-001",
    title: "Corduroy Overshirt Jacket",
    price: "£95.00",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/jackets",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "brown",
    tags: ["classic"],
  },
  {
    id: "prod-os-002",
    title: "Balloon Sleeve Cotton Blouse",
    price: "£65.00",
    image: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "white",
    tags: ["classic"],
  },
  {
    id: "prod-os-003",
    title: "Draped Wrap Midi Dress",
    price: "£115.00",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "green",
    tags: ["minimal"],
  },
  {
    id: "prod-os-004",
    title: "High Rise Straight Leg Trousers",
    price: "£89.00",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/trousers",
    affiliateUrl: "",
    category: "Trousers",
    color: "black",
    tags: ["classic"],
  },
  {
    id: "prod-os-005",
    title: "Cropped Merino Wool Cardigan",
    price: "£110.00",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "pink",
    tags: ["classic"],
  },
  {
    id: "prod-os-006",
    title: "Bias Cut Satin Slip Dress",
    price: "£125.00",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/dresses",
    affiliateUrl: "",
    category: "Dresses",
    color: "burgundy",
    tags: ["luxe"],
  },
  {
    id: "prod-os-007",
    title: "Ribbed Fitted Long Sleeve Top",
    price: "£45.00",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/tops",
    affiliateUrl: "",
    category: "Tops",
    color: "red",
    tags: ["minimal"],
  },
  {
    id: "prod-os-008",
    title: "Chunky Textured Knit Sweater",
    price: "£120.00",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/knitwear",
    affiliateUrl: "",
    category: "Knitwear",
    color: "grey",
    tags: ["minimal"],
  },
  {
    id: "prod-os-009",
    title: "Fitted High Waist Performance Leggings",
    price: "£65.00",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/activewear",
    affiliateUrl: "",
    category: "Activewear",
    color: "black",
    tags: ["sporty"],
  },
  {
    id: "prod-os-010",
    title: "Longline Tailored Wool Coat",
    price: "£180.00",
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&q=80",
    brand: "& Other Stories",
    retailer: "& Other Stories",
    productUrl: "https://www.stories.com/en_gbp/clothing/coats",
    affiliateUrl: "",
    category: "Coats & Jackets",
    color: "beige",
    tags: ["classic"],
  },
];
